version: "3.9"

services:
  db:
    image: maggich/bd_itstep_game:latest
    container_name: BD_ForGame
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: